# Generated by Django 4.1.5 on 2023-01-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DcmDialCode',
            fields=[
                ('number_range_skey', models.FloatField(primary_key=True, serialize=False)),
                ('number_range', models.CharField(blank=True, max_length=100, null=True)),
                ('number_range_type', models.CharField(blank=True, max_length=5, null=True)),
                ('number_range_start_date', models.DateField(blank=True, null=True)),
                ('number_range_stop_date', models.DateField(blank=True, null=True)),
                ('number_range_owner_id', models.CharField(blank=True, max_length=100, null=True)),
                ('number_range_owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('host_name', models.CharField(blank=True, max_length=30, null=True)),
                ('gen_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('bt_charge_band_code', models.CharField(blank=True, max_length=10, null=True)),
                ('cost_category', models.CharField(blank=True, max_length=5, null=True)),
                ('rounding_rule', models.CharField(blank=True, max_length=10, null=True)),
                ('rounding_rule_description', models.CharField(blank=True, max_length=100, null=True)),
                ('threshold', models.CharField(blank=True, max_length=100, null=True)),
                ('service_description', models.CharField(blank=True, max_length=50, null=True)),
                ('origin_based_rating', models.CharField(blank=True, max_length=1, null=True)),
                ('traffic_type', models.CharField(blank=True, max_length=10, null=True)),
                ('itct_rating_type', models.CharField(blank=True, max_length=1, null=True)),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('country_iso_code', models.CharField(blank=True, max_length=3, null=True)),
                ('country_idd_code', models.CharField(blank=True, max_length=6, null=True)),
                ('source_system', models.CharField(blank=True, max_length=100, null=True)),
                ('insert_timestamp', models.DateTimeField(blank=True, null=True)),
                ('update_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('current_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'DCM_DIAL_CODE',
                'managed': False,
            },
        ),
    ]
