# Generated by Django 4.1.5 on 2023-02-03 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcmdata', '0002_dcmauditlog_dcmdialcodeoffcom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DcmAuditLog',
        ),
    ]
