# Generated by Django 4.1.5 on 2023-02-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcmtest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DcmFileAuditStatusLog',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('file_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('file_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('file_type', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=1000, null=True)),
                ('destination', models.CharField(blank=True, max_length=1000, null=True)),
                ('process_config_id', models.FloatField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=1000, null=True)),
                ('error', models.CharField(blank=True, max_length=1000, null=True)),
                ('record_count', models.FloatField(blank=True, null=True)),
                ('record_failed', models.FloatField(blank=True, null=True)),
                ('record_pass', models.FloatField(blank=True, null=True)),
                ('record_pass_warning', models.FloatField(blank=True, null=True)),
                ('file_extn', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'DCM_FILE_AUDIT_STATUS_LOG',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DcmAuditLog',
        ),
    ]
