# Generated by Django 4.1.5 on 2023-02-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcmtest', '0002_dcmfileauditstatuslog_delete_dcmauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfcomDialCode',
            fields=[
                ('number_range_skey', models.FloatField(primary_key=True, serialize=False)),
                ('number_block', models.CharField(blank=True, max_length=1000, null=True)),
                ('block_status', models.CharField(blank=True, max_length=1000, null=True)),
                ('number_block_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('cp_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('number_length', models.CharField(blank=True, max_length=1000, null=True)),
                ('allocation_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('insert_timestamp', models.DateTimeField(blank=True, null=True)),
                ('update_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=1000, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'OFCOM_DIAL_CODE',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DcmDialCodeOffcom',
        ),
    ]
